<?xml version="1.0"?>
<!--
THESE COMMANDS AUTO-GENERATE THE NECESSARY *.urdf / *.xml
rosrun xacro xacro -o my_spot.urdf my_spot.xacro
rosrun xacro xacro -o my_spot.xml my_spot.xacro
-->
<!-- Revolute-Revolute Manipulator -->
<robot name="my_spot" xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <!-- Constants for robot dimensions -->
  <xacro:property name="REFLECT" value="-1"/>
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.12" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="x_width_body" value="2.4" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="y_width_body" value="0.48" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="z_width_body" value="0.12" /> <!-- Square dimensions (widthxwidth) of beams -->

  <xacro:property name="x_width_shoulder_left" value="0.12" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="y_width_shoulder_left" value="0.24" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="z_width_shoulder_left" value="0.12" /> <!-- Square dimensions (widthxwidth) of beams -->

  <xacro:property name="x_width_upperarm_left" value="1.2" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="y_width_upperarm_left" value=".04" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="z_width_upperarm_left" value="0.12" /> <!-- Square dimensions (widthxwidth) of beams -->

  <xacro:property name="x_width_lowerarm_left" value="1.2" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="y_width_lowerarm_left" value=".04" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="z_width_lowerarm_left" value=".12" /> <!-- Square dimensions (widthxwidth) of beams -->

  <xacro:property name="height1" value="2.4" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1.2" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1.2" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="${z_width_lowerarm_left/2}" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="axel_offset_small" value="${y_width_upperarm_left/2}" /> <!-- Space btw top of beam and the each joint -->


</robot>
